Dockerfile
This fix upgrades remoting to 2.60, which is the latest version.
There are much changes since 2.52. The major ones are:
* Support of the JNLP3 protocol with encryption
* Memory leak fixes
* Fixes for several connectivity issues
Incomplete changelog is available here: https://github.com/jenkinsci/remoting/blob/stable-2.x/CHANGELOG.md
@reviewbybees @jenkinsci/code-reviewers
=> Upgrade remoting to 2.62

README.md
This PR creates a Readme for the current state of the DockerHub. `2.62` branches need to be revived in the repository since we have automatic builds now. Maybe it's better to rename them to something like `2.x` and `2.x-alpine` since @jglick wants to change the version naming approach in Remoting 2.x
@reviewbybees, esp. @ndeloof and @carlossg
=> Create README for the repository

Dockerfile
Otherwise git clone fails in alpine
https://issues.jenkins-ci.org/browse/JENKINS-41137
```
$ docker run -ti --rm --entrypoint git jenkins/slave:alpine clone git@github.com:carlossg/selenium-example.git
Cloning into 'selenium-example'...
error: cannot run ssh: No such file or directory
fatal: unable to fork
```
=> [JENKINS-41137] Add openssh-client for git clone from ssh to work

Dockerfile
With master image it works
```
$ docker run -ti --rm jenkinsci/slave:3.7-1 wget https://www.google.com
--2017-06-11 11:39:53--  https://www.google.com/
Resolving www.google.com (www.google.com)... 216.58.198.36, 2a00:1450:4002:807::2004
Connecting to www.google.com (www.google.com)|216.58.198.36|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.google.es/?gfe_rd=cr&ei=CSw9WceLPMbA8geCooOYBg [following]
--2017-06-11 11:39:53--  https://www.google.es/?gfe_rd=cr&ei=CSw9WceLPMbA8geCooOYBg
Resolving www.google.es (www.google.es)... 216.58.205.67, 2a00:1450:4002:808::2003
Connecting to www.google.es (www.google.es)|216.58.205.67|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’ …
```
=> Add openssl to alpine to allow downloads from https sites

Dockerfile, README.md
=> [JENKINS-44114] - Update to remoting 3.10 and add workdir support

Dockerfile
It creates a branch for Java 11 and Remoting. Apparently works as is
https://issues.jenkins-ci.org/browse/JENKINS-51986
=> [JENKINS-51986] - Introduce a Java 11 packaging for the Debian image

README.md
Documents #34 
https://issues.jenkins-ci.org/browse/JENKINS-51986
=> [JENKINS-51986] - Add Java 11 support to documentation

Dockerfile
The Jenkins UID and GID has to be same as the Jenkins Docker image otherwise Docker-in-Docker can not be used, by mounting `/var/run/docker.sock`.
Jenkins Docker image settings: https://github.com/jenkinsci/docker/blob/master/Dockerfile#L7
Resolves #32
=> Fixed Jenkins UID and GID to be consistent with the Jenkins Docker image

Dockerfile-windows, Dockerfile-windows-jdk11, Dockerfile-windows-nanoserver, Dockerfile-windows-nanoserver-jdk11, README.md, build.ps1, build.sh
- Currently only supports Windows Server Core
- Files in place to support nanoserver, but more testing needs to be done
- Both JDK 8 and JDK 11 images are supported
Feedback welcome!
=> Initial commit of Windows docker image support.

Dockerfile, Dockerfile-alpine, Dockerfile-jdk11
HOME is normally controlled by the "system"[1] and should match what the user's home directory in `/etc/passwd` is. Overwriting this value with `ENV` in this docker image causes some surprises when the user is changes with `USER` in a docker image derived `FROM` this image. Unfortunatly, docker still doesn't allow to "reset" environment variables (https://github.com/moby/moby/issues/3465), so if I want to change the user, I need to remember to also update `HOME`.
Long story short: This removes the global preset for `HOME`, so `HOME` does function as expected.
[1] I think in normal UNIX sessions, login is responsible for that, but in the case of docker, docker itself takes care of that..
=> Drop global HOME environment variable

Dockerfile
The [latest version](https://github.com/jenkinsci/remoting/releases/tag/remoting-3.34) of `remoting` contains changes allowing to connect to a headless Jenkins like Jenkinsfile Runner.
We need this to run Jenkinsfile Runner on Kubernetes in combination with the Kubernetes plugin.
@jeffret-b @oleg-nenashev
=> Update Remoting from 3.29 to 3.35

Dockerfile, README.md
Renamed the slave.jars to agent .jars.  I wasn't sure how to update the location of this image on docker hub to jenkins/agent.
=> [JENKINS-42846] - Rename slave.jar to agent.jar, keep symbolic link for compatibility

README.md
We do not longer use OpenJDK 8 in all images.I would like to cleanup the README to avoid confusion
=> Remove the confusing OpenJDK 8 reference from the README

Dockerfile
@oleg-nenashev : Refers this: https://github.com/jenkinsci/docker-jnlp-slave/pull/100
=> [JENKINS-42846] - Fix the agent.jar symbolic link in the JDK 8 image

Dockerfile, Dockerfile-alpine, Dockerfile-jdk11
Fixes agents. 3.35-1 is completely broken, and emergency reviews will be appreciated
=> [JENKINS-42846] - Fix regressions in images after slave.jar => agent.jar renaming with improper symlink

Dockerfile-alpine, Dockerfile-jdk11, Dockerfile-windows, Dockerfile-windows-jdk11, Dockerfile-windows-nanoserver, Dockerfile-windows-nanoserver-jdk11
@oleg-nenashev In https://github.com/jenkinsci/docker-slave/pull/74 I missed to adjust the other Dockerfiles as well 😕
Sorry for that.
=> Switch all Dockerfiles to remoting 3.35

README.md
Use full id for the Windows containers until they are in the jenkins dockerhub org.
=> Fix Windows container paths

README.md
=> Amend Java 11 documentation to reflect the GA status of Java 11 in Jenkins

Jenkinsfile, make.ps1
The build occurs on the docker hub builds, so we don't need to build and push on trusted.
=> Don't build on trusted and image cleanup

Jenkinsfile
Currently all PR's will publish windows images, making it only happen on master
=> Only publish on master

Dockerfile, Dockerfile-alpine, Dockerfile-jdk11, Dockerfile-windows, Dockerfile-windows-jdk11, Dockerfile-windows-nanoserver, Dockerfile-windows-nanoserver-jdk11, README.md
Jenkins 2.204.1 LTS includes remoting 3.36
Tested default (Debian 9), Alpine Linux, and JDK 11.
Did not test Windows images, though I have tested Windows agents using remoting 3.36 with both JNLP and ssh connections.
=> Use remoting 3.36

LICENSE
There is a lot of License files in the repos with different owners, so I just used "Jenkins contributors". The purpose of this PR is to retrigger Release Drafter and to cut 3.36-1
=> Add explicit MIT License to the Root of the repo

Dockerfile, Dockerfile-alpine, Dockerfile-jdk11, Dockerfile-windows, Dockerfile-windows-jdk11, Dockerfile-windows-nanoserver, Dockerfile-windows-nanoserver-jdk11, LICENSE
This Remoting version removes old, deprecated, unsupported protocols versions 1, 2, and 3. And the unused plain protocol. See the [Remoting changelog](https://github.com/jenkinsci/remoting/releases) for full details.
=> Update to Remoting 3.40.

Dockerfile, Dockerfile-alpine, Dockerfile-jdk11, Dockerfile-windows, Dockerfile-windows-jdk11, Dockerfile-windows-nanoserver, Dockerfile-windows-nanoserver-jdk11
This Remoting release adds support for WebSockets. See the [Remoting changelog](https://github.com/jenkinsci/remoting/releases/tag/remoting-4.0) for full details.
=> [JEP-222] - Update to Remoting 4.0. Add support for WebSockets.

Dockerfile, Dockerfile-alpine, Dockerfile-jdk11, Dockerfile-windows, Dockerfile-windows-jdk11, Dockerfile-windows-nanoserver, Dockerfile-windows-nanoserver-jdk11
See [SECURITY-1659](https://jenkins.io/security/advisory/2020-01-29/). Also see the [Remoting changelog](https://github.com/jenkinsci/remoting/releases/tag/remoting-4.0.1) (which says the same thing.)
=> Update to Remoting 4.0.1 for security release.

Dockerfile-jdk11-buster, Makefile, tests/tests.bats
Debian 9 although stable is quite old in terms of up-to-date versions of software.
=> Provide image which is based on Debian 10/buster

Dockerfile, Dockerfile-alpine, Dockerfile-jdk11, Dockerfile-jdk11-buster, Dockerfile-windows, Dockerfile-windows-jdk11, Dockerfile-windows-nanoserver, Dockerfile-windows-nanoserver-jdk11
See [JENKINS-61409](https://issues.jenkins-ci.org/browse/JENKINS-61409).
Also see the [Remoting changelog](https://github.com/jenkinsci/remoting/releases/tag/remoting-4.3).
Related to jenkinsci/jenkins#4601.
=> Update to Remoting 4.3 for WebSocket large payload fix.

Dockerfile-windows, Dockerfile-windows-jdk11, Dockerfile-windows-nanoserver, Dockerfile-windows-nanoserver-jdk11, Jenkinsfile, README.md, make.ps1, tests/agent.Tests.ps1, tests/test_helpers.psm1
- Use AdoptOpenJDK instead of plain OpenJDK
- Fix issues with passwords expiring
- Fix user creation issue
- Add Git and Git LFS
- Update versions
- Add tests
=> Update Windows containers

11/buster/Dockerfile, 11/stretch/Dockerfile, 11/windows/nanoserver-1809/Dockerfile, 11/windows/windowsservercore-1809/Dockerfile, 8/alpine/Dockerfile, 8/stretch/Dockerfile, 8/windows/nanoserver-1809/Dockerfile, 8/windows/windowsservercore-1809/Dockerfile, make.ps1, tests/agent.Tests.ps1
- Cleanup MAINTAINER usage which is deprecated
- Fix JAVA_HOME for nanoserver
- Use 1809 for Windows OS version
- Update Windows tests similar to jnlp and ssh agents
- Change Windows tags to have jdk version at front when specified
=> Windows updates and cleanup

8/buster/Dockerfile, Makefile, README.md
Follow-up to https://github.com/jenkinsci/docker-slave/pull/105 by @krufab. The change adds Debian Buster image and switches both Java 8 and Java 11 images to Buster.
=> Switch Debian images to Buster by default

README.md
Our documentation is still referencing `jenkins4eval` images, but we already have official images in place. Looks like it is a leftover after the build flow finalization by @Slide
=> Update documentation to reference official Windows image tags

README.md
subj., finishing the documentation cleanup
=> [INFRA-1105] - Fix reference to the renamed Inbound Agent image, remove obsolete badges

make.ps1
This change restricts deployments only to tags documented in https://github.com/jenkinsci/docker-agent#configurations . We should definitely start shipping short handles for Windows images later, but now it is needed to prevent collision of the `latest` tag.
Closes #125
=> Stop shipping undocumented Windows image tags

11/windows/nanoserver-1809/Dockerfile, 11/windows/windowsservercore-1809/Dockerfile, 8/windows/nanoserver-1809/Dockerfile, 8/windows/windowsservercore-1809/Dockerfile
On ci.j.io we saw an issue where the path for a repo was returned with an extra slash at the beginning of the repository path. This was not seen with the non-busybox version in testing by @MarkEWaite. This updates to use the non-busybox version of MinGit to avoid these issues.
=> Fix issue with paths when using MinGit busybox

11/windows/nanoserver-1809/Dockerfile, 11/windows/windowsservercore-1809/Dockerfile, 8/windows/nanoserver-1809/Dockerfile, 8/windows/windowsservercore-1809/Dockerfile
Reverts jenkinsci/docker-agent#130
The non busybox version does not work on nanoserver. I would like to revert this.
=> Revert "Fix issue with paths when using MinGit busybox"

8/buster/Dockerfile
stretch-backports was brought in by https://github.com/jenkinsci/docker-agent/pull/61 to support the install of git-lfs which for buster is also in stable
=> Remove stretch-backports from apt sources

README.md
Documentation patch + changelog entry. Contributors for the changelog @slide 
Closes #129
=> Add a Debian Stretch distribution, based on the openjdk:8-jdk-stretch image

11/alpine/Dockerfile, Makefile
This PR adds a Dockerfile based on adoptopenjdk/openjdk11:alpine
inspired by the work from @slide in jenkinsci/docker
=> Add openjdk11-alpine Dockerfile

11/windows/nanoserver-1809/Dockerfile, 11/windows/windowsservercore-1809/Dockerfile, 8/windows/nanoserver-1809/Dockerfile, 8/windows/windowsservercore-1809/Dockerfile, make.ps1
Various contributors have found that there are issues running git during tests inside the jnlp-agents containers we use with ACI. This fixes the issue. I tested with git-client-plugin and workflow-cps-global-lib-plugin
/cc @dwnusbaum @MarkEWaite
=> Fix for git in nanoserver containers

8/alpine/Dockerfile, README.md
Same as https://github.com/jenkinsci/docker/pull/975 and https://github.com/jenkinsci/docker-ssh-agent/pull/59 . Package difference concerns apply here as well
=> Switch the Alpine JDK8 image to AdoptOpenJDK

11/windows/nanoserver-1809/Dockerfile, 8/windows/nanoserver-1809/Dockerfile
As of right now, the nanoserver images produce the following error when trying to fetch an repository using ssh.
```
stderr:       0 [main] ssh (1552) C:\mingit\usr\bin\ssh.exe: *** fatal error - unable to load netapi32.dll, Win32 error 126
```
This pull requests adds the required files from the `servercore` image, to fix this issue.
=> Fix SSH in the Windows Nanoserver images

8/alpine/Dockerfile
Latest JDK 8 release
See also https://github.com/jenkinsci/docker/pull/1008
See also https://github.com/jenkinsci/docker-ssh-agent/pull/67
=> Use JDK 8u272 on Alpine

make.ps1
Similar to https://github.com/jenkinsci/docker-agent/pull/158
Fail the build if any issues with publishing the docker images
It does not fail fast to be able to provide as many details as possible.
=> [Hactoberfest] Fail the execution at the end if any publishing failures

11/alpine/Dockerfile, 11/buster/Dockerfile, 11/stretch/Dockerfile, 11/windows/nanoserver-1809/Dockerfile, 11/windows/windowsservercore-1809/Dockerfile, 8/alpine/Dockerfile, 8/buster/Dockerfile, 8/stretch/Dockerfile, 8/windows/nanoserver-1809/Dockerfile, 8/windows/windowsservercore-1809/Dockerfile, make.ps1, tests/agent.Tests.ps1
The 4.6 version of Remoting contains minor improvementx, mostly involving dependency updates.
See the [Remoting changelog](https://github.com/jenkinsci/remoting/releases/tag/remoting-4.6) and the corresponding [core PR](https://github.com/jenkinsci/jenkins/pull/5043).
I think I caught all of the places that need to be updated.
=> Upgrade to Remoting 4.6.

.gitignore, Jenkinsfile, Makefile
Transform TAP output to JUnit using the https://www.npmjs.com/package/tap-xunit library within a docker container. 
NOTE: It does support windows for the time being.
Easy to visualise the test output in the build UI.
```
$ make build-alpine
$ make test-alpine
...
$ ls -1 target/
junit-results-alpine.xml
results-alpine.tap
$ head -3 target/junit-results-alpine.xml
<?xml version="1.0"?>
<testsuites>
<testsuite tests="5" failures="0" errors="0" name="jenkinsci.docker-agent.alpine.Default">
```
=> [Hacktoberfest] Support JUnit format for Linux tests

11/windows/nanoserver-1809/Dockerfile, 11/windows/windowsservercore-1809/Dockerfile, 8/windows/nanoserver-1809/Dockerfile, 8/windows/windowsservercore-1809/Dockerfile
Updtes JDK versions on Windows to 8u292 and 11.0.11-b9. The ltsc2019 images are based on images built in our infra, I did not update those as the correct tags do not exist.
=> Update JDK versions on windowsservercore-1809 and nanoserver

11/windows/nanoserver-1809/Dockerfile, 11/windows/windowsservercore-1809/Dockerfile, 11/windows/windowsservercore-ltsc2019/Dockerfile, 8/windows/nanoserver-1809/Dockerfile, 8/windows/windowsservercore-1809/Dockerfile, 8/windows/windowsservercore-ltsc2019/Dockerfile
https://github.com/git-lfs/git-lfs/releases/tag/v2.13.3 says:
> updates some dependencies to versions which lack a security issue (which did not affect Git LFS)
Note the crucial phrase, "which did not affect Git LFS".  This update silences security scanners that complain because one of the go libraries (golang.org/x/crypto v0.0.0-20190426145343-a29dc8fdc734) has been updated to a version that does not have a security issue (golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9), even though that security issue does not affect git-lfs.
The git lfs version available with Alpine Linux 3.14.0 is 2.13.1.  It uses the earlier library, but I believe we can rely on the statement from the git lfs release notes that they are not affected by the security issue.
=> Use git lfs 2.13.3 on Windows

11/buster/Dockerfile, 8/alpine/Dockerfile, 8/buster/Dockerfile, README.md, build.sh, docker-bake.hcl
- Use Java 11 in default images
- Use AdoptOpenJDK 11.0.12 instead of 11.0.11
- Use AdoptOpenJDK 8u302 instead of 8u292
=> Use Java 11 in default Docker images

docker-bake.hcl
Unfortunately jlink + QEMU don't work together on s390x or ppc64le.
=> Disable ppc64 and s390x

.gitmodules, tests/test_helpers.bash, tests/tests.bats
Same as https://github.com/jenkinsci/docker-agent/pull/194
.git/config doesn't seem to be updating due to https://newbedev.com/git-clone-works-git-submodule-fails-permission-denied
[bats-assert](https://github.com/bats-core/bats-assert) will give us the actual error when tests fail, unlike in https://github.com/jenkinsci/docker-agent/pull/193 where the locale is broken but it just says test failed.
we already use it in https://github.com/jenkinsci/docker
=> Integrate bats-assert + fix SC issues in test

11/windows/nanoserver-1809/Dockerfile, 11/windows/windowsservercore-ltsc2019/Dockerfile, 8/windows/windowsservercore-ltsc2019/Dockerfile
Artifactory 'native' file browser has been disabled on our instance.
They are 'tracking' the bug at https://www.jfrog.com/jira/browse/RTFACT-26216
But apparently they just tell you to turn the browser off if there's an issue.
Happy with the solution anyway as it's about 5x faster with it turned off
=> Remove user agent hack

11/alpine/Dockerfile, 11/archlinux/Dockerfile, 11/bullseye/Dockerfile, 11/windows/nanoserver-1809/Dockerfile, 11/windows/windowsservercore-ltsc2019/Dockerfile, 8/alpine/Dockerfile, 8/bullseye/Dockerfile, 8/windows/windowsservercore-ltsc2019/Dockerfile, docker-bake.hcl, tests/agent.Tests.ps1, tests/test_helpers.bash, tests/tests.bats
Replaces https://github.com/jenkinsci/docker-agent/pull/141 which was heavily conflicted
=> Add metadata labels

17/bullseye/Dockerfile, 8/bullseye/Dockerfile, docker-bake.hcl, tests/tests.bats
Build will fail till https://github.com/docker-library/official-images/pull/10945 is merged
=> Add java 17 preview

17/alpine/Dockerfile, docker-bake.hcl
adding jdk17 for alpine 
tests performed locally
- `make test-alpine_jdk17`
- java -version
```
$ docker run jenkins/agent:alpine-jdk17 java -version
openjdk version "17.0.1" 2021-10-19
OpenJDK Runtime Environment (build 17.0.1+12-alpine-r0)
OpenJDK 64-Bit Server VM (build 17.0.1+12-alpine-r0, mixed mode)
```
Fixes #221
=> Add Java 17 Alpine

11/windows/nanoserver-1809/Dockerfile, 11/windows/windowsservercore-ltsc2019/Dockerfile, 17/windows/nanoserver-1809/Dockerfile, 17/windows/windowsservercore-ltsc2019/Dockerfile, 8/windows/nanoserver-1809/Dockerfile, 8/windows/windowsservercore-ltsc2019/Dockerfile
- Use MinGit 2.35,3, not 2.33.1 (avoid complaints about a git CVE that does not affect Jenkins agents in Docker)
- Use git lfs 3.1.2 on Windows (use most recent release, consistent with controller in Docker)
=> Use latest git for Windows

11/windows/nanoserver-1809/Dockerfile, 11/windows/windowsservercore-ltsc2019/Dockerfile, 17/windows/nanoserver-1809/Dockerfile, 17/windows/windowsservercore-ltsc2019/Dockerfile, 8/windows/nanoserver-1809/Dockerfile, 8/windows/windowsservercore-ltsc2019/Dockerfile
Updates git lfs on our Windows Docker agent images for CVE-2022-24826.  Does not update Linux versions of git lfs because they are not vulnerable to CVE-2022-24826.
https://www.cve.org/CVERecord?id=CVE-2022-24826 reports that
> On Windows, if Git LFS operates on a malicious repository with a `..exe` file as well as a file named `git.exe`, and `git.exe` is not found in PATH, the `..exe` program will be executed, permitting the attacker to execute arbitrary code.
Git LFS 3.1.3 changelog:
https://github.com/git-lfs/git-lfs/blob/032dca8ee69c193208cd050024c27e82e11aef81/CHANGELOG.md
Git LFS 3.1.4 changelog:
https://github.com/git-lfs/git-lfs/releases/tag/v3.1.4
- ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~
=> Use git lfs 3.1.4, not 3.1.2

11/windows/nanoserver-1809/Dockerfile, 11/windows/windowsservercore-ltsc2019/Dockerfile, 17/windows/nanoserver-1809/Dockerfile, 17/windows/windowsservercore-ltsc2019/Dockerfile, 8/windows/nanoserver-1809/Dockerfile, 8/windows/windowsservercore-ltsc2019/Dockerfile
MinGit 2.36.0 includes fixes from 2.35.3 and more.
See https://github.com/git-for-windows/git/releases/tag/v2.36.0.windows.1
=> Use MinGit 2.36.0 on Windows, not 2.35.3

11/alpine/Dockerfile, 17/alpine/Dockerfile, 8/alpine/Dockerfile
This PR switched the base image of the Alpine agents (JDK8, JDK11 and JDK17) from the stock "Alpine" to the official "eclipse-temurin" alpine variant.
It has the following benefits:
- Strict control of the JDK used, to control the version, as we were using the "latest" version as per the usual Alpine package manager style. "Latest" version is fine for some tools like `ca-certificates`, but in the case of the JDK, it is important to know which version is used or not.
- Faster and simplified builds for JDK11 and JDK17. We were using `jlink` to generate a custom JVM installation compliant with `musl` as no eclipse temurin Alpine image was available back then. It was convenient but being able to use the "stock" installation simplifies the Dockerfiles.
- ~[ ] Link to relevant issues in GitHub …
=> feat(alpine) switch base image to official eclipse-temurin (alpine)

17/bullseye/Dockerfile, docker-bake.hcl
I added `linux/arm/v7` to `debian_jdk11` and `debian_jdk17` on the `docker-bake.hcl` file.
I also had to make a change in `17/bullseye/Dockerfile` because it wouldn't build by cause of a `jmods: Value too large for defined data type` error.
It now builds correctly for me when issuing: 
```bash
docker buildx bake -f docker-bake.hcl debian_jdk11
```
or 
```bash
docker buildx bake -f docker-bake.hcl debian_jdk17
```
=> Add `arm32` images to the build

11/windows/nanoserver-1809/Dockerfile, 11/windows/windowsservercore-ltsc2019/Dockerfile, 17/windows/nanoserver-1809/Dockerfile, 17/windows/windowsservercore-ltsc2019/Dockerfile, 8/windows/nanoserver-1809/Dockerfile, 8/windows/windowsservercore-ltsc2019/Dockerfile
See the [mailing list announcement](https://groups.google.com/g/git-for-windows/c/M-_QnmeLXuo/m/HXfg1blKAgAJ).
Changelog: [GitHub](https://github.com/git-for-windows/git/releases/tag/v2.37.1.windows.1)
Fixes [CVE-2022-31012](https://github.com/git-for-windows/git/security/advisories/GHSA-gjrj-fxvp-hjj2) and CVE-2022-29187
CVE-2022-31012:
https://github.com/git-for-windows/git/security/advisories/GHSA-gjrj-fxvp-hjj2
"Git for Windows' installer can be tricked into executing an untrusted binary"
Since we don't use the Windows installer for git, we should not be
vulnerable to this issue.
CVE-2022-29187: Unpublished
=> Use MinGit 2.37.1

README.md, docker-bake.hcl
See Alpine 3.16 release notes at
* [Alpine 3.16.0 release notes](https://alpinelinux.org/posts/Alpine-3.16.0-released.html)
* [Alpine 3.16.1 release notes](https://alpinelinux.org/posts/Alpine-3.16.1-released.html)
Alpine 3.16.1 includes an openssl CVE fix and a busybox CVE fix.
* busybox [CVE-2022-30065](https://security.alpinelinux.org/vuln/CVE-2022-30065)
* openssl [CVE-2022-2097](https://security.alpinelinux.org/vuln/CVE-2022-2097)
The same fixes are available in Alpine 3.15.4 if we prefer to stay with Alpine 3.15.  I'm not aware of any compelling reason to remain with Alpine 3.15.
=> Use Alpine 3.16 instead of Alpine 3.15

docker-bake.hcl
The upstream image for Alpine is now 3.16.2, rather than 3.16.1
- N/A Link to relevant issues in GitHub or Jira
The upstream versions for [jdk-11](https://github.com/adoptium/containers/blob/6ca246080b385f7d114f1c452264fe094d4d6203/11/jdk/alpine/Dockerfile.releases.full#L20), [jdk-8](https://github.com/adoptium/containers/blob/6ca246080b385f7d114f1c452264fe094d4d6203/8/jdk/alpine/Dockerfile.releases.full#L20), and [jdk-17](https://github.com/adoptium/containers/blob/6ca246080b385f7d114f1c452264fe094d4d6203/17/jdk/alpine/Dockerfile.releases.full#L20) all point to "alpine:3.16", which according to the [alpine official image page](https://hub.docker.com/_/alpine) is an alias of 3.16.2, rather than 3.16.1
- N/A Ensure you have provided tests - that demonstrates feature works or fixes the …
=> feature/Update referenced Alpine versions

.github/dependabot.yml
Java 8 was removed in earlier pull requests.  No value to checking dependencies on a Java version that is no longer supported.
=> Remove Java 8 dependency checking

Makefile, docker-bake.hcl
IBM no longer provides the PowerPC agents that we use to test and verify PowerPC support. Can't support an architecture that we can't test.
=> Drop PowerPC 64 support (ppc64le)

Jenkinsfile
This PR is the twin of https://github.com/jenkinsci/docker-inbound-agent/pull/280.
It ensures that only tag-based build are deploying to the Dockerhub to avoid overriding accidentally.
It also disables the pollSCM which was causing trouble on the remote system.
It's a first step forward fixing the JDK8 tags build with JDK11 issues.
=>  chore(pipeline) only deploy to DockerHub on tag-triggered builds

17/bullseye/Dockerfile, docker-bake.hcl
Fixes #308.  Use platform dependent image by default to get correct java runtime.
Use native java runtime when on arm32 to get around jmods error:
"jmods: Value too large for defined data type" error
- ~Link to relevant pull requests, esp. upstream and downstream changes~
- ~Ensure you have provided tests - that demonstrates feature works or fixes the issue~
=> Fix ARM64 Java in JDK17 Bullseye

11/archlinux/Dockerfile, 11/bullseye/Dockerfile, 11/windows/windowsservercore-ltsc2019/Dockerfile, 17/bullseye/Dockerfile, 17/windows/windowsservercore-ltsc2019/Dockerfile
In order to ensure that we can track the JDK versions with any tool such as Updatecli (or renovabot), this PR ensures that the JDK version is always specified on the same way to Dockerfiles by using a build argument `JAVA_VERSION`.
Please note that:
- Archlinux is now using the same JDK (fixed) version as Debian (e.g. Eclipse Temurin built from the official image).
- There is no "centralized" version to avoid repetition (like it is currently for the remoting version).
----
- ~[] Link to relevant issues in GitHub or Jira~
- ~[] Link to relevant pull requests, esp. upstream and downstream changes~
- ~[ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue~
=> chore: ensure that JAVA_VERSION is always specified through a Docker build argument

.github/dependabot.yml, .github/workflows/updatecli.yaml, updatecli/updatecli.d/jdk11.yaml, updatecli/updatecli.d/jdk17.yaml, updatecli/values.github-action.yaml
This PR introduces automatic version tracking of JDK11 and JDK17 (for now) using updatecli.
Merging this PR would trigger a new JDK11 update PR at least (JDK17 17.0.5 is not available as Docker image yet for Eclipse Temurin).
=> chore: track JDK versions (11 and 17) with updatecli

tests/tests.bats
Fix https://github.com/jenkinsci/docker-agent/issues/304
=> chore(linux tests) remove deprecated jdk17-only check

11/alpine/Dockerfile, 11/archlinux/Dockerfile, 11/bullseye/Dockerfile, 11/windows/nanoserver-1809/Dockerfile, 11/windows/windowsservercore-ltsc2019/Dockerfile, 17/alpine/Dockerfile, 17/bullseye/Dockerfile, 17/windows/nanoserver-1809/Dockerfile, 17/windows/windowsservercore-ltsc2019/Dockerfile
This PR fixes a set of hadolint/shellcheck violations on the images.
Tried to proceed 1 commit per rule, so we can easily rollback only one.
I'm not sure yet how to efficiently load hadolint recursively on ALL `Dockerfile` though.
=> chore: fix hadolint/shellcheck violations

11/alpine/Dockerfile, 11/archlinux/Dockerfile, 11/bullseye/Dockerfile, 17/alpine/Dockerfile, 17/bullseye/Dockerfile, tests/tests.bats
This PR fixes #153 but is blocked by #320 .
It adds `curl` on all the Linux images + the root CA certificates (to ensure any HTTPS website can be used with `curl`).
It also stop using `curl` to download the remoting: the `Dockerfile` directive `ADD` is used instead to benefit from BuildX optimization, benefit from improved caching and simplify instructions (less layers, less code and faster builds).
Please note that the `ADD` instruction will soon support checksum https://docs.docker.com/engine/reference/builder/#verifying-a-remote-file-checksum-add---checksumchecksum-http-src-dest.
=> feat(linux) add curl

11/archlinux/Dockerfile, 11/bullseye/Dockerfile, 17/bullseye/Dockerfile, tests/tests.bats
With the help of @dduportal I added the minimal list of packages that are needed to be able to clone via ssh for the `Debian` image.
It's an attempt to solve #322.
The list of packages brought by installing git is:
```bash
git-man libcurl3-gnutls liberror-perl libgdbm-compat4 libgdbm6 libperl5.32 perl perl-modules-5.32
``` 
We're missing at least  `openssh-client` .
The list of packages brought by installing git was:
```bash
git-man less libbsd0 libcbor0 libcurl3-gnutls libedit2 liberror-perl libfido2-1 libgdbm-compat4 libgdbm6 libmd0 libperl5.32 libx11-6 libx11-data libxau6 libxcb1 libxdmcp6 libxext6 libxmuu1 netbase openssh-client patch perl perl-modules-5.32
xauth
```
```bash
openssh-client patch less netbase
```
We added [two …
=> fix(debian) Add missing packages to allow git cloning by ssh

17/bullseye/Dockerfile, LICENSE, docker-bake.hcl
Related to https://github.com/jenkinsci/docker-agent/issues/323 and https://github.com/jenkinsci/docker-agent/issues/308.
This PR reverts #310 and fixes #308 with a similar approach but with the "conditionnality" of the `arm/v7` directly inside the `Dockerfile` 's `jre-build` stage.
While reading https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/, I confirmed @carpnick 's analysis about the `BUILDPLATFORM`. But it seems that Docker provides another variable which is `TARGETPLATFORM` which is populated with the value we expect.
https://docs.docker.com/engine/reference/builder/#automatic-platform-args-in-the-global-scope shows the documentation reference with an exemple on "how to" use this variable as a build argument: is is what this PR does. …
=> fix(debian_jdk17) revert #310 and use `TARGETPLATFORM` to detect if arm/v7 or not

.github/workflows/updatecli.yaml, updatecli/updatecli.d/jdk11.yaml, updatecli/updatecli.d/jdk17.yaml
- Bumps the GitHub actions for update to latest `2.15.0` which features the 0.38.0 version of updatecli
- Simplify the conditions
=> chore(updatecli) adapt manifest for v0.38.0

Makefile, updatecli/updatecli.d/bats.yaml
This PR ensures that updatecli tracks the version of bats, the shell framework used for testing the Linux images.
Please note that:
- This PR has no functionnal change
- The updatecli checks will fail because it searches for the pattern on the `master` branch, but the pattern is changed as part of the PR. It means that I'll have to check for updatecli "success" once merged. If I force updatecli to ignore SCM locally, the expected result is the following:
```console
TARGETS
========
setBatsVersionInMakefile
------------------------
**Dry Run enabled**
⚠ updated the [dry run] content of the file "Makefile"
--- Makefile
+++ Makefile
@@ -52,7 +52,7 @@
@set -x; make --silent show | jq -r '.target | path(.. | select(.platforms[] | contains("linux/$(ARCH)"))?) | add'
bats:
-       git clone …
```
=> chore(updatecli) tracks bats version

README.md
By default, the image is using `Etc/UTC`. A user wants to use another timezone (c.f. [#291](https://github.com/jenkinsci/docker-inbound-agent/issues/291).
I explain briefly how to use another one while creating a new image derived from `jenkins/agent`.
This is a follow-up to #337 where I added the `tzdata` package.
This PR and the #337 will replace my first attempt (see #334).
- ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~
=> feat(documentation) Adds a small paragraph describing how to use another timezone

11/alpine/Dockerfile, 17/alpine/Dockerfile
With the latest (#341 #342 and #343) the tests regarding `tzdata` [failed](https://github.com/jenkinsci/docker-agent/pull/343/checks?check_run_id=10031726733) for Alpine Linux:
```bash
jenkinsci.docker.alpine_jdk11.Default.#8 [docker.io/jenkins/agent:alpine] 'tzdata' is correctly installed
jenkinsci.docker.alpine_jdk17.Default.#8 [docker.io/jenkins/agent:alpine-jdk17] 'tzdata' is correctly installed
```
In the [Dockerfile](https://github.com/jenkinsci/docker-agent/blob/master/11/alpine/Dockerfile#L24) we build the image from `eclipse-temurin:11.0.17_8-jdk-alpine`. This version now uses Alpine `3.17` and no more `3.16`.
In Alpine `3.16` the `tzdata` package used to contain the `zdump` binary we're using in our tests.
In Alpine `3.17` it has moved to the `tzdata-utils` package.
When this is …
=> fix(alpine) Alpine 3.17 `tzdata` package doesn't contain `zdump` anymore

updatecli/updatecli.d/bats.yaml, updatecli/updatecli.d/jdk11.yaml, updatecli/updatecli.d/jdk17.yaml, updatecli/updatecli.d/remoting.yaml
As per https://github.com/updatecli/updatecli/releases/tag/v0.40.0, the directive `pullrequests` in updatecli is deprecated in favor of `actions`, along with their `kind` namings.
This PR changes the manifests to remove depreciation messages. Nothing functional.
=> chore(updatecli) change deprecated directives with v0.40.x

11/windows/nanoserver-1809/Dockerfile, 11/windows/windowsservercore-ltsc2019/Dockerfile, 17/windows/nanoserver-1809/Dockerfile, 17/windows/windowsservercore-ltsc2019/Dockerfile
This PR updates (manually) the Git version in the 4 Windows images to 2.39.1 (patch 1) - https://github.com/git-for-windows/git/releases/tag/v2.39.1.windows.1.
Please note that updatecli should manage this in the near future: the tricky part is to capture and handle the patch, but that should be doable.
=> feat(windows) bump git to 2.39.1 patch 1

11/windows/nanoserver-1809/Dockerfile, 11/windows/windowsservercore-ltsc2019/Dockerfile, 17/windows/nanoserver-1809/Dockerfile, 17/windows/windowsservercore-ltsc2019/Dockerfile, updatecli/updatecli.d/git-windows.yml
This PR enable `updatecli` to track version of `git` for Windows images only.
It should automate pull requests such as #369 in the future (only human review would be required).
Please note that the image code had to be changed in order to support the 2 kinds of download URL available for the official Git SCM:
- If the "windows patch" is `1`, then the download filename does not have any mention of the patch (for instance version `2.39.1` with patch `1` is `MinGit-2.39.1-64-bit.zip`).
- If the "windows patch " is 2 or more, then the filename has the patch as the 4th digit (for instance version `2.39.0` with patch `2` is `MinGit-2.39.0.2-64-bit.zip`).
=> chore(windows) track git version using updatecli and manages all windows patches

11/alpine/Dockerfile, 11/archlinux/Dockerfile, 11/bullseye/Dockerfile, 11/windows/nanoserver-1809/Dockerfile, 11/windows/windowsservercore-ltsc2019/Dockerfile, 17/alpine/Dockerfile, 17/bullseye/Dockerfile, 17/windows/nanoserver-1809/Dockerfile, 17/windows/windowsservercore-ltsc2019/Dockerfile, tests/agent.Tests.ps1, tests/tests.bats
Caught by https://github.com/jenkinsci/docker-inbound-agent/pull/340, the environment variable `user` is absent for the `jenkins/agent` base image.
Exposing it in the image metadata allows users, building from this image, to switch back and forth between `root` (or `ContainerAdministrator` on Windows) in their `Dockerfile`.
Also added test on both Linux and Windows for this.
=> feat: expose default image user to the environment variable `user`

Makefile, docker-bake.hcl
The following are the steps I have automated to build Jenkins CI controller and agents for a foreign architecture. My build workstation architecture is amd64.
I use ```docker.io/multiarch/qemu-user-static``` to emulate the build processes only, I do not use full ```qemu-system-ppc64le``` emulation of a complete Operating System. It is unecessary and slow to attempt full emuluation of kernel etc. to build software, a container is much more efficient and you are always using the latest code, versus maintaining a full Operating System.
If the Jenkins infrastructure team is not already doing so, I suggest switching to this containerized method of building foreign target architecures, as these steps work well for s390x and aarch64 (just substitute ```ARCH=ppc64le``` below with ```ARCH=s390x``` …
=> Adding ppc64le support back into the Jenkins CI agent Docker build.

docker-bake.hcl
The Alpine container image uses the Alpine version that is provided by the Elclipse Temurin Alpine container image.  That container image was upgraded from 3.16 to 3.17 months ago.  We didn't detect that version upgrade. We don't have a test that checks the Alpine version matches the tag we are creating on Dockerhub.
This is a short term solution, since it doesn't add any check to verify the Alpine version included in the Eclipse Temurin Alpine container matches the version we use to create the Dockerhub tag.
Since Alpine 3.18.0 has released, we can expect that the next Eclipse Temurin update (11.0.20, 17.0.8) in about 3 months will deliver Alpine 3.18.0 instead of 3.17.3.
Fixes https://github.com/jenkinsci/docker-agent/issues/415
Confirmed that Alpine 3.17 is included in the Temurin …
=> Label Alpine container with correct version number

build-windows.yaml, build.ps1, tests/agent.Tests.ps1
This PR is an extract of https://github.com/jenkinsci/docker-agent/pull/409 + custom adjustments
Its goal is to update the windows tooling to:
- Get the image to build from `docker-compose` instead of searching for `Dockerfile` recursively
- Increase separation of concerns and efficiency: 
- Delegates build to `docker-compose` even when building only one image
- Utilizes `docker tag` after the build instead of rebuilding (even if cached)
- Cleanup code:
- Remove deprecated or unused directives
- Factorize code
* on my local machine, ran the command `.\build.ps1 -Target test` to test "all" + CI checks
* on my local machine, ran the commands `.\build.ps1 -Target test -Build jdk11-nanoserver-1809`, `.\build.ps1 -Target test -Build jdk17-nanoserver-1809`, `.\build.ps1 -Target test -Build …
=> chore(windows) rely on docker-compose for test phase

.github/CODEOWNERS
Follow up of https://github.com/jenkinsci/docker/pull/1632 and #391 
As per https://github.com/jenkinsci/docker/issues/1559#issuecomment-1453514549, @ksalerno99 stepped-in to help to add the ppc64le architecture on this image (and also Docker agents).
This PR adds as a (co-) code owner for the debian images (ref #391)
Many thanks for the contributions and help!
Once merged, i'll take care of adding @ksalerno99 in the repository as contributor.
=> add ksalerno99 as code owner for the debian Dockerfile

docker-bake.hcl, updatecli/updatecli.d/jdk11.yaml, updatecli/updatecli.d/jdk17.yaml
This PR follows up #409 to fix the updatecli manifest which tracks the JDK versions.
As HCL is not supported out of the box by updatecli (ref. https://github.com/updatecli/updatecli/issues/534), I've factorized the JAVA_VERSION in the `docker-bake.hcl` file to allow easier file regexp matching.
The updatecli check will fail on this PR, for both JDK11 and JDK17 manifest, because [updatecli only check against the remote principal branch](https://github.com/updatecli/updatecli/issues/465) instead of the local change. Since `docker-bake.hcl` was changed, it won't see the changed version.
So I tested locally by commenting out the `scmid: ` key of the failing targetn which gave me the following results:
<details>
<summary>Click to see JDK11 result</summary>
```console
TARGETS
======== …
```
=> chore(updatecli) fix JDK version tracking - fixup of #409

.github/dependabot.yml, updatecli/updatecli.d/git-windows.yml, updatecli/updatecli.d/remoting.yaml
As part of #409, the location of the `Dockerfile` were changed.
Despite #418 , there still had components with invalid locations: this PR aims at fixing them:
- Dependabot
- Updatecli manifest for the git version (causing build failures in GHA)
- Updatecli manifest for the remoting version (causing build failures in GHA)
=> chore: fix Dockerfile location on the last items - fixup of #409

.github/dependabot.yml, alpine/Dockerfile
@MarkEWaite detected in #415 that there was a mismatch in the naming of our Alpine Docker image, and solved it in #416.
@dduportal took some time to guide me in figuring out the problem may need a more permanent fix.
We are getting the Alpine version shipped with Eclipse Temurin. We don't take into account the `ALPINE_TAG` set in the `docker-bake.hcl` file. Damien's proposal was to do as we do with Debian, proceed with two stages.
One stage to get the Temurin build, and one to get the correct (i.e. defined in the `docker-bake`) Alpine version.
The (optional?) next step would be to use `jlink` as we do in the Debian image.
The only testing I have done is run locally after building the image:
```bash
docker run --rm jenkins/agent:alpine-jdk17 cat /etc/os-release
NAME="Alpine Linux" …
```
=> fix(alpine) The Alpine Dockerfile does not use the `ALPINE_TAG` arg

updatecli/updatecli.d/alpine.yaml
`updatecli/updatecli.d/alpine.yaml` now checks for a `3.x` update for Alpine, with the help of github then docker hub.
This is a work in progress, thanks to the guidance from @dduportal, after #421 (and more specifically in his [comment](https://github.com/jenkinsci/docker-agent/pull/421#issuecomment-1552674986)).
The main target has not been reached yet, as we're only changing values in `alpine/Dockerfile`, which is nice, but not enough.
We have to change the value in `docker-bake.hcl`, which is not the case yet. I will have to investigate.
I've used a dry run and it detected a new version:
```bash
updatecli diff --config updatecli/updatecli.d/alpine.yaml --values updatecli/values.github-action.yaml
+++++++++++
+ PREPARE +
+++++++++++
Loading Pipeline "updatecli/updatecli.d/alpine.yaml" …
```
=> chore(alpine): Uses `updatecli` to stay up to date

Jenkinsfile
This PR activates `failFast` so the build stop whenever there is an error instead of waiting for the completion of every stage.
Replayed with a voluntary error in the `linux` stage: https://ci.jenkins.io/job/Packaging/job/docker-agent/job/PR-446/3/
<details><summary>diff</summary>
```diff
--- old/Jenkinsfile
+++ new/Jenkinsfile
@@ -8,6 +8,7 @@
stages {
stage('Build') {
+            failFast true
parallel {
stage('Windows') {
agent {
@@ -71,8 +72,9 @@
stage('Prepare Docker') {
steps {
sh '''
-                                docker buildx create --use
-                                docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
+                                exit 1
+                                // docker buildx create --use
+                                // …
```
=> chore(build): activate `failFast` for parallel stages

windows/windowsservercore-ltsc2019/Dockerfile
This PR switches from an `eclipse-temurin` base image to a `powershell:windowsservercore` one, a multi-stage image like it's done for nanoserver.
Note: while all tests are passing, this can potentially be a breaking change.
Close #429 
https://ci.jenkins.io/job/Packaging/job/docker-agent/job/PR-442/1/pipeline-console/?selected-node=28
```[tasklist]
```
=> feat: use a multi-stage image for Windows Server Core

Jenkinsfile
This PR removes the unnecessary `timestamps()` call as noted in the build logs:
> The timestamps step is unnecessary when timestamps are enabled for all Pipeline builds. 
```[tasklist]
```
=> chore(build): remove unnecessary `timestamps()` call

.github/workflows/updatecli.yaml, build-windows.yaml, updatecli/updatecli.d/jdk11.yaml, updatecli/updatecli.d/jdk17.yaml
Minor fixups of #445 + remove updatecli's depreciation warnings  avoid empty PR due to double quotes
=> chore(updatecli) fixups of JDK manifests and remove depreciation warnings

build.ps1, tests/agent.Tests.ps1, tests/test_helpers.psm1, updatecli/updatecli.d/jdk11.yaml, updatecli/updatecli.d/jdk17.yaml
This PR fixes Pester tests by passing `WINDOWS_VERSION_TAG` env var as build arg in the docker tests. (It would use a 1809 image otherwise, causing the following error: "The container operating system does not match the host operating system.")
It also contains a cleanup of updatecli manifests and debug messages.
Fixup extracted from #441, follow-up of #445
Only this change: https://ci.jenkins.io/job/Packaging/job/docker-agent/view/change-requests/job/PR-458/1/
With an additional Windows 2022 image in #441: https://ci.jenkins.io/job/Packaging/job/docker-agent/job/PR-441/96/
```[tasklist]
```
=> chore(tests) fixup build to pass Windows version image tag as build arg for Pester docker tests

build.ps1
This PR outputs the list of Windows images and tags to be processed in the logs, ex:
```
= PREPARE: List of images and tags to be processed:
{
"jdk17-windowsservercore-ltsc2019": {
"Tags": [
"jdk17-windowsservercore-ltsc2019",
"3131.vf2b_b_798b_ce99-1-jdk17-windowsservercore-ltsc2019"
]
},
"jdk11-windowsservercore-ltsc2019": {
"Tags": [
"jdk11-windowsservercore-ltsc2019",
"3131.vf2b_b_798b_ce99-1-jdk11-windowsservercore-ltsc2019",
"windowsservercore-ltsc2019"
]
},
"jdk17-nanoserver-1809": {
"Tags": [
"jdk17-nanoserver-1809",
"3131.vf2b_b_798b_ce99-1-jdk17-nanoserver-1809",
]
},
"jdk11-nanoserver-1809": {
"Tags": [
"jdk11-nanoserver-1809",
"3131.vf2b_b_798b_ce99-1-jdk11-nanoserver-1809",
"nanoserver-1809",
]
}
}
```
```[tasklist]
```
=> chore(build): output in logs the list of Windows images and tags to be processed

Jenkinsfile
Revert #446, not useful in insight.
=> chore: disable `failFast`

updatecli/updatecli.d/alpine.yaml, updatecli/updatecli.d/jdk11.yaml, updatecli/updatecli.d/jdk17.yaml, updatecli/updatecli.d/remoting.yaml
Since [0.55.0](https://github.com/updatecli/updatecli/releases/tag/v0.55.0), updatecli has a [native HCL resource](https://www.updatecli.io/docs/plugins/resource/hcl/).
This PR updates the manifest to replace the tedious "file resource with matchpattern regex" in favor of the native HCL.
=> chore(updatecli) track docker-bake variables with the native HCL resource instead of file

updatecli/updatecli.d/jdk11.yaml, updatecli/updatecli.d/jdk17.yaml
fixup of #459 which changes the internal structure of the `build-windows.yaml`, breaking the updatecli builds.
Fixes #490
=> chore(updatecli) fixup of #459 for JDK11 and JDK11 manifests

alpine/21/Dockerfile, debian/21/Dockerfile, docker-bake.hcl
Add jdk21 preview images
This is something that's been discussed here https://github.com/jenkinsci/docker-inbound-agent/issues/395 in an effort to have alpine based arm64 images for the inbound agent.
Built locally
```[tasklist]
```
=> Add preview images for jdk21

updatecli/scripts/check-jdk.sh, updatecli/updatecli.d/jdk21.yaml
As we haven't seen "regular" Temurin JDK21 releases yet, I propose to track the early access versions, in case we receive another one before the official JDK21 release. This should be easy to modify once we move out of the early access mode. This follows PR #492 and issue https://github.com/jenkinsci/docker-inbound-agent/issues/395.
I have added an `updatecli `file to track the JDK21 version, as well as a shell file (borrowed from one of the infra repositories and slightly modified, thanks @smerle33) to help us ensure that the crafted URL is correct.
While not strictly necessary, it's a nice addition in my opinion. If we ever change our minds regarding the way we build the images, transitioning from Temurin's own images to only their JDK binaries, this could prove to be helpful in the …
=> feat(dependencies): Tracks JDK21 early access releases.

debian/21/Dockerfile, docker-bake.hcl
After discussing with @ksalerno99 yesterday during the [Platform SIG meeting](https://www.jenkins.io/sigs/platform/), I considered that adding support for a few platforms for JDK21 would be beneficial.
I then propose to add `"linux/ppc64le"`, `"linux/armv/v7"`  and `"linux/s390x"` as new target platforms for our JDK21 preview images.
`docker buildx bake --file docker-bake.hcl debian_jdk21`
- ~~Link to relevant issues in GitHub or Jira~~
- ~~Link to relevant pull requests, esp. upstream and downstream changes~~
=> feat(platforms): Adds ppc64le and s390x archs for JDK21.

docker-bake.hcl
[Today](#498), we added new architectures for `debian_jdk21`, but I forgot to add `debian_jdk21` to the existing groups (arm32, ppc64le and s390x).
My bad.
- ~~Link to relevant issues in GitHub or Jira~~
- ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~
=> fix(docker): Adds "debian_jdk21" in s390x and ppc64le groups.

tests/agent.Tests.ps1, updatecli/updatecli.d/git-lfs-windows.yaml, windows/nanoserver/Dockerfile, windows/windowsservercore/Dockerfile
This PR fixes the `git: 'lfs' is not a git command.` error noticed in https://github.com/jenkinsci/docker-agent/pull/502#issuecomment-1717648730 when using the version 3.4.0 of git-lfs by adding git to the `PATH` earlier then using git-lfs.exe installer instead of `git.exe lfs install`.
It also adds a test ensuring git-lfs (and thus git) is correctly installed.
Supersedes and closes #502
https://ci.jenkins.io/job/Packaging/job/docker-agent/job/PR-503/11/
```[tasklist]
```
=> fix(windows) bump `git-lfs` to 3.4.0 and fix its installation

updatecli/updatecli.d/git-lfs-windows.yaml
This PR is an `updatecli` fixup of #503 for the `git-lfs` manifest
=> chore(updatecli) correct regexp error to fix git-lfs manifest

docker-bake.hcl
This PR fixes the tags by replacing `bullseye` by `bookworm` in the docker-bake.
Follow-up of #499, closes #515 
```[tasklist]
```
=> fix(debian): replace `bullseye` by `bookworm` in tags

README.md
The documentation was mentioning bullseye while the container images we build are limited to bookworm.
Related to:
* #499
* #516
Confirmed that all the tags referenced in the updated documentation exist on Dockerhub and report the correct operating system when they are executed.
=> Replace bullseye with bookworm in docs

Jenkinsfile
This PR increase the build timeout from 30 minutes to 60 minutes, as the last release https://github.com/jenkinsci/docker-agent/releases/tag/3148.v532a_7e715ee3-13 was aborted on trusted.ci.jenkins.io while building its last Windows image due to a timeout.
```[tasklist]
```
=> chore: increase build timeout from 30 to 60 minutes

README.md, archlinux/Dockerfile, build.ps1, docker-bake.hcl
This PR sets Java 17 as the default JDK and short tags like what has been done in the official Docker image: https://github.com/jenkinsci/docker/pull/1724
Changes:
- Set JDK17 as default in Linux and Windows builds for short tags
- Add `latest-bookworm` tag (to be coherent with the other Linux flavors)
- ~~Add archlinux-17 images (related: #422)~~ removed in https://github.com/jenkinsci/docker-agent/pull/520/commits/7fc8b833084800037957267c4cbd8c8a379d50b4, can be reverted or added in another PR if needed.
- Update README with JDK17 images as default short tags (closes #489)
```[tasklist]
```
=> breaking: set Java 17 as default

debian/21/Dockerfile, debian/Dockerfile
This fixes issue #527 by removing the removal of man-pages and documentation files from Debian based Dockerfiles.
To be done...
```[tasklist]
```
=> Fix issue #527: Remove removal of man-pages and documentation files.

build.sh
Similar what has been added to the Windows logs with https://github.com/jenkinsci/docker-agent/pull/461, this PR shows the output of `docker buildx -f docker-bake.hcl --print linux` before building or publishing Linux images (but not before testing, should already been shown previously), listing all their info.
<details><summary>Example of output:</summary>
```json
{
"group": {
"default": {
"targets": [
"linux"
]
},
"linux": {
"targets": [
"alpine_jdk11",
"alpine_jdk17",
"alpine_jdk21",
"archlinux_jdk11",
"debian_jdk11",
"debian_jdk17",
"debian_jdk21"
]
}
},
"target": {
"alpine_jdk11": {
"context": ".",
"dockerfile": "alpine/Dockerfile",
"args": {
"ALPINE_TAG": "3.18.4",
"JAVA_VERSION": "11.0.20.1_1",
"VERSION": "3160.vd76b_9ddd10cc"
},
"tags": [
"docker.io/jenkins/agent:alpine-jdk11", …
```
=> chore: print the docker-bake targets for linux

updatecli/updatecli.d/alpine.yaml
Quick hotfix of #521 to correct the `updatecli` process which is failing on the `master` branch
=> chore(updatecli) remove reference to a deleted file for Alpine

updatecli/scripts/check-jdk.sh, updatecli/updatecli.d/jdk21-preview.yaml, updatecli/updatecli.d/jdk21.yaml
This PR is a follow-up of #521, complement of #535, similar to https://github.com/jenkinsci/docker/pull/1741
https://github.com/jenkinsci/docker-agent/actions/runs/6606391106/job/17942546905?pr=536
<details><summary>Corresponding updatecli logs:</summary>
```
########################################################
########################################################
SOURCES
=======
getLatestJDK21PreviewVersion
----------------------------
Searching for version matching pattern ".*-ea-.*"
✔ Git tag "jdk-21.0.1+12-ea-beta" found matching pattern ".*-ea-.*" of kind "regex"
CONDITIONS:
===========
checkIfReleaseIsAvailable
-------------------------
The shell 🐚 command "/bin/sh /tmp/updatecli/bin/e178f4342f912570a17f53f2079a8f8a53445ca928f785971065f2d450977844.sh" ran successfully with …
```
=> chore(updatecli): add `jdk21-preview` manifest and adapt `check-jdk.sh` script

debian/preview/Dockerfile
This PR fixes the preview (EA) release download link in the Dockerfile of the debian_jdk_21_preview image.
Related: https://github.com/jenkinsci/docker-agent/pull/537
```[tasklist]
```
=> fix(jdk21-preview): correct `JAVA_MAJOR_VERSION` extraction for the EA release link

build.ps1
This PR adds a `DryRun` switch argument that can be passed to the Windows build.ps1 script, allowing to run it in dry-run mode.
Normal build: https://ci.jenkins.io/job/Packaging/job/docker-agent/job/PR-545/9/
Replayed build on Windows only, with `-DryRun` activated: https://ci.jenkins.io/job/Packaging/job/docker-agent/job/PR-545/8/console
<details><summary>Replay diff:</summary>
```diff
--- old/Jenkinsfile
+++ new/Jenkinsfile
@@ -24,7 +24,7 @@
axes {
axis {
name 'IMAGE_TYPE'
-                        values 'linux', 'nanoserver-1809', 'nanoserver-ltsc2019', 'nanoserver-ltsc2022', 'windowsservercore-1809', 'windowsservercore-ltsc2019', 'windowsservercore-ltsc2022'
+                        values 'nanoserver-1809', 'nanoserver-ltsc2019', 'nanoserver-ltsc2022', 'windowsservercore-1809', …
```
=> chore(Windows): add `-DryRun` option to build.ps1 script

.github/workflows/updatecli.yaml
This PR bumps the GHA to this release: https://github.com/updatecli/updatecli-action/releases/tag/v2.48.0
Should allow https://github.com/jenkinsci/docker-agent/pull/556 to go back to green thanks to https://github.com/updatecli/updatecli/releases/tag/v0.65.1, and especially
- https://github.com/updatecli/updatecli/pull/1729
```[tasklist]
```
=> Bump updatecli-action to v2.48.0 (updatecli 0.65.1)

Makefile, README.md
This PR replaces `master` by `controller` in README.md and remove an unused `IMAGE_NAME_AGENT` variable name (set to `jenkins4eval/slave`) from the Makefile.
```[tasklist]
```
=> chore: replace `master` by `controller` and remove unused `IMAGE_NAME_AGENT` variable

README_agent.md, README_inbound-agent.md, windows/nanoserver/Dockerfile, windows/windowsservercore/Dockerfile
This PR fixes a few remaining references to the docker-inbound-agent repository.
Supersedes and closes https://github.com/jenkinsci/docker-agent/pull/583
Follow-up of:
- #570
Ref:
- #569 
No code change.
```[tasklist]
```
=> chore: fix repository references

docker-bake.hcl
Reverts jenkinsci/docker-agent#773 because build fails consistently on Windows after this merge
=> Revert "Bump JDK21 version to 21.0.2_13"

docker-bake.hcl, updatecli/scripts/check-jdk.sh
This is a follow-up to #772.
@MarkEWaite [noted](https://github.com/jenkinsci/docker-agent/pull/772#issuecomment-2002012356) that we should use the official build versions for the architectures that have moved out of preview.
@dduportal then noted that the only one that was left was s390x.
I'm proposing this small change to remove `s390x`'s JDK from the preview and start using the official Temurin builds.
I noticed that there was no `arm32 `defined in [check-jdk.sh](https://github.com/jenkinsci/docker-agent/blob/master/updatecli/scripts/check-jdk.sh#L32), even though it is supposed to be called by the [`jdk21-preview` manifest](https://github.com/jenkinsci/docker-agent/blob/master/updatecli/updatecli.d/jdk21-preview.yaml#L42).
I'm not sure how we got this working for `arm32 `in the first …
=> feat(JDK21) Use official Temurin build for `linux/s390x`

alpine/Dockerfile, debian/Dockerfile, debian/preview/Dockerfile
This PR integrates jlink improvement from https://github.com/jenkinsci/docker/pull/1857.
> adapted it to be POSIX compliant as the Alpine ash shell doesn't support arrays
Notes:
- I removed the TARGETPLATFORM check in Alpine images as we're not publishing any arm/v7 image of this kind.
- The Debian "preview" Dockerfile doesn't need these changes as it's used to build only one JDK (21).
Extracted from:
- https://github.com/jenkinsci/docker-agent/pull/786
Local builds + CI
```[tasklist]
```
=> chore: jlink improvements from jenkinsci/docker

README_agent.md, docker-bake.hcl
(Draft, see open questions below)
After using the docker agents for much time, i found i was actually using less optimal tags then the ones i randomly discovered in the dockerhub tag search
1. This is a reformatting of the readme to hopefully make the tags that are available to be used more clear. 
2. Also added 1 more tag in the bake file to align with the same amount of tags created on alpine and same format.
3. Open questions:
- which i thought about too late: Is there an actual need for so many JDK flavors?
- Deprecate archlinux? released tags seem old
(I suggest to review using some Markdown previewer)
Related #777 
N/A
```[tasklist]
```
=> chore(doc): Reformat readme tags

jenkins-agent, jenkins-agent.ps1
https://github.com/jenkinsci/docker-agent/pull/802#issuecomment-2098889201
This deprecates existing environment variables allowing to set options to `agent.jar`. Going forward, this will ease addition or removal of options to `agent.jar` without impacting these launcher scripts.
```[tasklist]
```
=> Introduce `REMOTING_OPTS` to pass arbitrary options to remoting on startup via an environment variable

updatecli/scripts/check-jdk.sh, updatecli/updatecli.d/debian.yaml
This PR removes remnants of jdk21-preview preventing updatecli to run correctly: https://github.com/jenkinsci/docker-agent/actions/runs/9548455384/job/26315680774
Follow-up of:
- #822 
cc @gounthar 
CI
=> hotfix(updatecli): remove remnant of jdk21-preview

debian/Dockerfile
This should hopefully™️ help retrieving correct changelog information in Renovate PRs such as https://github.com/jenkinsci/helm-charts/pull/1135. It also fixes broken `source` link in the PR table.
Not tested yet. Based on [Renovate documentation](https://docs.renovatebot.com/key-concepts/changelogs/#how-renovate-detects-changelogs), this URL must be correct, so that it can detect the changelog.
=> Fix Debian-based Docker image `org.opencontainers.image.source` label

Jenkinsfile
Reverts jenkinsci/docker-agent#844 as per https://github.com/jenkins-infra/helpdesk/issues/4192#issuecomment-2270821972 (we now have a DockerHub mirror)
=> Revert " chore(Jenkinsfile) increase DockerHub rate limit with authentication"

alpine/Dockerfile, archlinux/Dockerfile, debian/Dockerfile, tests/tests_agent.bats, windows/nanoserver/Dockerfile, windows/windowsservercore/Dockerfile
https://github.com/jenkinsci/docker-agent/issues/858 (this will be moved at some point)
Fixes issue with environment variables named USER being set to user due to it being merged with the variable set in the Dockerfile.
- [ N/A ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
=> Bugfix: Fix regression where environment variables set to USER would be lowercased to user.

README_inbound-agent.md, jenkins-agent
Fixes #859
Currently, the Jenkins agent jar file location is hardcoded in `/usr/share/jenkins/agent.jar`.
The jar file may be downloaded by the user who does not have write permission to directory, `/usr/share/jenkins`.
It would be great if the location can be customized in the environment variable.
=> Add support for Jenkins agent jar file location in the environment variable JENKINS_AGENT_FILE

adoptium-get-jdk-link.sh, adoptium-install-jdk.sh
Recent PRs did fail to build with error returned while downloading the Temurin archives.
This changes introduces the 2 following element to avoid these build failures:
- Enable (exponential backoff) retries 
- Have `curl` printing the error when it happens (otherwise the use of the `--silent` flags hides the information)
=> chore(temurin Adoptium install scripts) provide visibility for `curl` and retry downloads

Jenkinsfile
This PR fixes the deployment error specified in https://github.com/jenkinsci/docker-agent/pull/827#issuecomment-2371752625
None (for now). Gotta run a replay with no "push" on trusted.ci
- ~[ ] Ensure that the pull request title represents the desired changelog entry~ (skiping changelog)
- ~[ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue~ (hard to test)
=> chore(Jenkinsfile) fix `withEnv` syntax error

updatecli/scripts/ubi9-latest-tag.sh, updatecli/updatecli.d/rhel-ubi9.yaml
After [@lemeurherve's work](https://github.com/jenkinsci/docker-agent/pull/880) on the `updatecli` manifest to keep UBI9 updated in the docker bake file and Dockerfile, it became clear something wasn't working as expected when trying to find the latest version of the UBI9 container with the default `updatecli` behavior.  
I then took Hervé's manifest and transitioned it into using a shell script to find the "right" version.  
I discovered a [Swagger description](https://catalog.redhat.com/api/containers/v1/ui/#/Repositories/graphql.images.get_images_by_repo) that led me to the correct API endpoint.  
This endpoint allowed me to query the `ubi9` containers, sorted by the last update date and filtered by the `latest` tag.  
As a result, I obtained the version `9.4-1214.1726694543`.  
The …
=> feat(updatecli): Track UBI9 version

README_agent.md
This PR replaces the relative link introduced in #888 by an absolute one as this README is used on https://hub.docker.com/r/jenkins/agent/
Ref:
- https://github.com/jenkinsci/docker-agent/pull/888#issuecomment-2390721078
N/A
=> doc: use absolute link in README_agent.md

updatecli/scripts/ubi9-latest-tag.sh, updatecli/updatecli.d/rhel-ubi9.yaml
This is a follow-up PR to #906 by @dduportal.
I started from [his work](https://github.com/jenkinsci/docker-agent/pull/906/files#diff-02266124aa9dfc148fb3f492952ca4add1a7d498a00e8ec0bec0699ec52d0bcbR20) and altered the `jq` query.
`updatecli diff --debug --config ./updatecli/updatecli.d/rhel-ubi9.yaml --values ./updatecli/values.github-action.yaml 2>&1`
=> chore(updatecli) fix UBI9 manifest 

docker-bake.hcl
This PR adds `linux_tags` and `windows_tags` functions to regroup Docker image tags definition so we don't have to change every target block when introducing a new JDK, and to avoid errors and/or inconsistencies.
It takes in account JDK in preview so we don't have to deal with it everywhere.
With #945, compared the output of `make show-linux` and `make show-windows` from the primary branch and from this PR branch, no change, same results.
```
ON_TAG=true BUILD_NUMBER=3 make show-linux | jq -r ".target | .[].tags | .[]" | sort
ON_TAG=true BUILD_NUMBER=3 make show-windows | jq -r ".target | .[].tags | .[]" | sort
```
Also checked the output when adding '25' to the `jdks_to_build` list to ensure the work done by @gounthar in #939 could use it without issue:
<details><summary>Linux …
=> chore: add tags functions to docker bake

Makefile, README.md, docker-bake.hcl
- add `show-%` Makefile target: allow debugging Windows targets on a Linux or MacOS machine.
- use `jdks_to_build` in `rhel_ubi9` bake target: follow-up of #890 
Extracted from:
- #944
Tested like #944 + CI
=> chore: add `show-%` Makefile target and use `jdks_to_build` in `rhel_ubi9` bake target

Makefile
This PR uses TOM config with buildx if executed on CI and if `/etc/buildkitd.toml` file exists to use registry mirrors.
Ref:
- https://github.com/jenkins-infra/helpdesk/issues/4585#issuecomment-2751406309
- https://github.com/jenkins-infra/jenkins-infra/pull/3938
- https://docs.docker.com/build/buildkit/configure/#registry-mirror
`make docker-init` + CI
=> chore: use TOML config with buildx to avoid DockerHub rate limits

Jenkinsfile
If the label `docker-highmem` label does not provide any agent on ci.jenkins.io, we don't want it to fall back on `linux` label, because it may lead to spinning up an arm64 machine which fails the build
Extracted from https://github.com/jenkinsci/docker-agent/pull/960 to provide a short term fix to failing builds, unrelated to the support of spot/retries
=> chore(Jenkinsfile) avoid using trusted.ci agent labels on ci.jenkins.io

Jenkinsfile
This PR changes the pipeline to support the new infrastructure agent labels pattern on ci.jenkins.io (ref. https://github.com/jenkins-infra/helpdesk/issues/4598 and https://github.com/jenkins-infra/pipeline-library/pull/917).
- Switch to scripted syntax to support the `retry()` with counter and agent failure detection (see the note below)
- Ensure that `trusted.ci.jenkins.io` Linux VM agent labels are not used on ci.jenkins.io which result in failed build due to CPU mismatch on ci.jenkins.io (since the `linux` label is too generic)
(edit) NOTE: The label `docker-highmem` is now using Spot instances (ref. https://github.com/jenkins-infra/helpdesk/issues/4598). In the current state (even with #961).
If the spot agent is reclaimed, the build fails on ci.jenkins.io.
This PR is about retrying …
=> chore(Jenkinsfile) add support for retries with non Spot VMs on ci.jenkins.io

Jenkinsfile
Removes the message
```
Did you forget the `def` keyword? WorkflowScript seems to be setting a field named parallelStages (to a value of type LinkedHashMap) which could lead to memory leaks or other issues.
```
Caused by #960
=> chore(Jenkinsfile) correct potential memory leak in the pipeline

windows/nanoserver/Dockerfile, windows/windowsservercore/Dockerfile
This PR sets `HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathEnabled` to 1, and git `core.longpaths` to `true` for all users instead of only the current one in Windows images.
Ref:
- #966
=> chore(windows): set `LongPathEnabled` registry entry

docker-bake.hcl, rhel/ubi9/Dockerfile, updatecli/scripts/ubi9-latest-tag.sh
The updatecli process is failing due to some change in the UBI 9 API response.  Rather than delay the availability of remoting 3309 and the latest operating system updates, I've created the updates myself.
Includes a change that needs to be reviewed by those who understand updatecli better than I do.  @gounthar or @dduportal or @lemeurherveCB would be great to review that proposed change.  The change works, but I am not confident that it is correct.
Confirmed that `make build` and `make clean` are both successful.
=> Bump UBI9 version to 9.5-1745848351

README.md, build.ps1, rhel/ubi9/Dockerfile, updatecli/scripts/ubi9-latest-tag.sh, windows/nanoserver/Dockerfile, windows/windowsservercore/Dockerfile
Update examples to Java 17.0.15
Use 21.0.7_6 instead of 21.0.3_9 in example comment.
Includes a change that needs to be reviewed by those who understand updatecli better than I do.  @gounthar or @dduportal or @lemeurherveCB would be great to review that proposed change.  The change works, but I am not confident that it is correct.
Copied the example output from current output samples.
=> Update examples to use most recent JDK versions

.github/workflows/updatecli.yaml
Looking at #980 and #978 , it is another example of us, maintainers, expecting a dependency to be proposed for update in a bump PR while `updatecli` did not run.
In this particular case, there was a failure in one of the `updatecli` manifests (UBI9)  which created confusion.
This PR is a proposal to change the schedule of the `updatecli` GitHub Action job so it runs once a day instead of once a week to solve this confusion.
=> chore(GHA) run `updatecli` once a day

updatecli/updatecli.d/jdk17.yaml
This PR adds rhel-ubi9, nanoserver and windowservercore Dockerfiles as targets of jdk17.yaml updatecli manifest as they weren't covered cf https://github.com/jenkinsci/docker-agent/pull/981#discussion_r2075478448, https://github.com/jenkinsci/docker-agent/pull/981/files#diff-8279a2baaa897bfb70dbfa0bf71f3599f7713f5da5d0b46a483488f3a590ab9eR32 and https://github.com/jenkinsci/docker-agent/pull/981/files#diff-2e09df7c118a78a0a7de0a6fa97be765befeced7c51ca4258f0de01943b3e069R32
Follow-up of:
- https://github.com/jenkinsci/docker-agent/pull/981#discussion_r2075478448
```
updatecli diff --config updatecli/updatecli.d/jdk17.yaml --values updatecli/values.github-action.yaml
```
=> chore(updatecli): add missing targets to jdk17 manifest

README_inbound-agent.md
This PR adds `REMOTING_OPTS` to the optional environment variables and deprecate others in inbound agent README.
Follow-up of:
- #809
N/A
=> doc: add `REMOTING_OPTS` optional env var and deprecate others in README

updatecli/updatecli.d/debian.yaml
We received an automatic PR for Debian Bookworm in #1050, even though we've transitioned to Trixie. To align with this change, we need to update the updatecli manifest accordingly.
Closes #1050
=> chore: Update Debian version from Bookworm to Trixie

README_agent.md, docker-bake.hcl
Fixes https://github.com/jenkinsci/docker-agent/issues/1059 by using "trixie" in the container image name instead of "bookworm".
Amends pull request:
* https://github.com/jenkinsci/docker-agent/pull/1051
Confirmed that generated container image names now look like this:
```
REPOSITORY              TAG                           IMAGE ID
jenkins/inbound-agent   jdk21                         ff4ddd1974c9
jenkins/inbound-agent   latest-jdk21                  ff4ddd1974c9
jenkins/inbound-agent   latest-trixie-jdk21           ff4ddd1974c9
jenkins/inbound-agent   trixie-jdk21                  ff4ddd1974c9
jenkins/inbound-agent   jdk17                         28bcb4477386
jenkins/inbound-agent   latest                        28bcb4477386
jenkins/inbound-agent   latest-jdk17 …
```
=> Use Trixie in the Debian container name, not Bookworm

alpine/Dockerfile, debian/Dockerfile, rhel/ubi9/Dockerfile
This PR simplify a bit the jlink version switch so we don't have to set a dot or not depending on the version status (GA with only a number, GA with a number and a dot, or beta with only a number).
`make test`
=> chore(linux): no dot in jlink version switch

Jenkinsfile, build.ps1
This PR splits the existing stage into "Build" and "Test".
Having separate stages allows a better understanding of the potential gains on each of those part when improving the building process.
Notes:
- Generated docker compose files are archived even if the tests fail
- As the `publish` target includes building the images, no need to call it first when only that one is running on trusted.ci.jenkins.io
- As there is no "test" phase for multi-arch build, no need to change it
Extracted from:
- #1068
- CI
PS: easier to review without whitespaces, see https://github.com/jenkinsci/docker-agent/pull/1071/files?diff=unified&w=1
=> chore(pipeline): split `Build and Test` stage
