jenkinsci/docker-agent

- Dockerfile
If this looks ok I'll merge into a new alpine branch @ndeloof
> Alpine image

- Dockerfile
just added the missing `-G` to the adduser command.
Good catch by  @jwieringa
> add Group flag

- Dockerfile
The issue has been originally reported to agents working in Kubernetes, so I think it is applicable here.
https://github.com/jenkinsci/remoting/blob/master/CHANGELOG.md#37
@reviewbybees
> Update to remoting 3.7 with JENKINS-42371

- README.md
> Noting usage via CommandLauncher

- README.md
See https://github.com/jenkinsci/durable-task-plugin/pull/49#discussion_r150907307 for background.
@reviewbybees
> Pass --init to docker-run so we run tini and reap zombies

- Dockerfile
Also change the maintainer to reflect the current state
Changelog: https://github.com/jenkinsci/remoting/blob/master/CHANGELOG.md#315
@reviewbybees @rysteboe
> Update Jenkins Remoting to 3.15

- Dockerfile
https://github.com/jenkinsci/remoting/blob/master/CHANGELOG.md#316
@reviewbybees @carlossg
> Update Jenkins Remoting to 3.16

- Dockerfile
To enable `ps -p` option
Fixes https://github.com/jenkinsci/docker-jnlp-slave/issues/65
See https://github.com/jenkinsci/durable-task-plugin/pull/75/files#r206999876 
[JENKINS-52847](https://issues.jenkins-ci.org/browse/JENKINS-52847)
> [JENKINS-52847] Add procps package to alpine

- Dockerfile
- Dockerfile-alpine
- Dockerfile-jdk11
> Upgrade to remoting 3.29

- Dockerfile
- Dockerfile-alpine
- Dockerfile-jdk11
> Add git-lfs to docker image

- Jenkinsfile
- build.sh
Let's check things look good
Very simplistic for now.
Should help avoid https://github.com/jenkinsci/docker-slave/pull/61 / #60 in the future. cc @tjanson
> Jenkinsfile calling simplistic build script

- Dockerfile
> Add Stretch Backports source to fix Git LFS install

- build.ps1
Remove nanoserver builds for now.
> Fix naming of org vs repo

- Jenkinsfile
Testing windows build of docker container
> Add build of Windows container

- Jenkinsfile
Set the DOCKERHUB_ORGANISATION environment variable correctly
> Set environment variable correctly

- Dockerfile-windows
- Dockerfile-windows-jdk11
- Dockerfile-windows-nanoserver
- Dockerfile-windows-nanoserver-jdk11
> This adds git to windows docker images to align them more with existing linux images

- Dockerfile-windows
- Dockerfile-windows-jdk11
- Dockerfile-windows-nanoserver
- Dockerfile-windows-nanoserver-jdk11
See issue #111 The password of jenkins user in Windows images expires after a few weeks.
> Let jenkins user's password in windows never expire.

- make.ps1
This fixes the publishing portion of make.ps1 to push the images correctly
> Fix publishing of image

- README.md
Might be useful to users. I need it to retrigger the release drafter, lazy mode.
> Reference Remoting changelogs from README

- README.md
Staged documentation update for the image renaming
> [INFRA-1105] - Rename the image to jenkins/agent

- Jenkinsfile
Adds the tag building code to the Jenkinsfile.
> Add tag build and publish for windows

- README.md
> Show GitHub stars and quick link on DockerHub landing

- 11/windows/nanoserver-1809/Dockerfile
- 11/windows/windowsservercore-1809/Dockerfile
- 8/windows/nanoserver-1809/Dockerfile
- 8/windows/windowsservercore-1809/Dockerfile
Uses wmic on servercore and sets no expiration on nanoserver
> Fix issue with Windows passwords expiring

- 11/windows/nanoserver-1809/Dockerfile
- 11/windows/windowsservercore-1809/Dockerfile
- 8/windows/nanoserver-1809/Dockerfile
- 8/windows/windowsservercore-1809/Dockerfile
- make.ps1
- tests/agent.Tests.ps1
- Missed setting up password expiry in one Dockerfile
- Added test case for checking password expiry
- Updated how make.ps1 finds builds
> Fix more issues with password expiry

- Jenkinsfile
- make.ps1
Relates to https://github.com/jenkinsci/docker-agent/pull/157
Generate JUnit output
> Support JUnit format for Windows tests

- make.ps1
Closes https://github.com/jenkinsci/docker-agent/issues/156
Fail the build if any test failures happened when running the windows tests.
It does not fail fast to be able to provide as many details as possible.
It does not fail if test failures at the moment
> [Hactoberfest] Fail the execution at the end if any test failures

- make.ps1
- tests/agent.Tests.ps1
This upgrades to Pester 5.x for tests on Windows.
> Upgrade to Pester 5

- 11/windows/nanoserver-1809/Dockerfile
- 11/windows/windowsservercore-1809/Dockerfile
- 11/windows/windowsservercore-ltsc2019/Dockerfile
- 8/windows/nanoserver-1809/Dockerfile
- 8/windows/windowsservercore-1809/Dockerfile
- 8/windows/windowsservercore-ltsc2019/Dockerfile
Update git & git lfs version to latest for windows. This helped to fix git hang issue
> Update git & git lfs version to latest for windows

- 11/alpine/Dockerfile
- 11/buster/Dockerfile
- 11/stretch/Dockerfile
- 11/windows/nanoserver-1809/Dockerfile
- 11/windows/windowsservercore-1809/Dockerfile
- 11/windows/windowsservercore-ltsc2019/Dockerfile
- 8/alpine/Dockerfile
- 8/buster/Dockerfile
- 8/stretch/Dockerfile
- 8/windows/nanoserver-1809/Dockerfile
- 8/windows/windowsservercore-1809/Dockerfile
- 8/windows/windowsservercore-ltsc2019/Dockerfile
Upgrade to Remoting 4.7. This version has been released for several weeks and been packaged into Jenkins for a couple of weeks.
> Upgrade to Remoting 4.7.

- 11/alpine/Dockerfile
- 11/buster/Dockerfile
- 11/windows/nanoserver-1809/Dockerfile
- 11/windows/windowsservercore-1809/Dockerfile
- 11/windows/windowsservercore-ltsc2019/Dockerfile
- 8/alpine/Dockerfile
- 8/buster/Dockerfile
- 8/windows/nanoserver-1809/Dockerfile
- 8/windows/windowsservercore-1809/Dockerfile
- 8/windows/windowsservercore-ltsc2019/Dockerfile
> Upgrade Remoting to 4.9

- 11/alpine/Dockerfile
- 11/archlinux/Dockerfile
- 11/bullseye/Dockerfile
- 8/bullseye/Dockerfile
- README.md
- docker-bake.hcl
See https://github.com/jenkinsci/docker/pull/1185
> Switch to eclipse temurin, build via jlink, switch to bullseye

- Jenkinsfile
> Setup multi-arch for when running on tag

- 11/bullseye/Dockerfile
- 17/bullseye/Dockerfile
- 8/bullseye/Dockerfile
- Use specific Debian version in JDK 17 image
- Use Debian bullseye 2022-02-28, not 2022-01-28
- ~~Link to relevant issues in GitHub or Jira~~
- ~~Link to relevant pull requests, esp. upstream and downstream changes~~
- ~~Ensure you have provided tests - that demonstrates feature works or fixes the issue~~
> Update OS images

- docker-bake.hcl
Most recent fixes, used in Jenkins controller Docker image
> Use Alpine 3.15.4, not 3.15.0

- README.md
- docker-bake.hcl
Closes #266
Removed the "-preview" listing from the `docker-bake.hcl` and the `README.md` files
- [N/A] Link to relevant pull requests, esp. upstream and downstream changes
- [N/A] Ensure you have provided tests - that demonstrates feature works or fixes the issue
> Remove "-preview" from Java 17 images

- docker-bake.hcl
missed in https://github.com/jenkinsci/docker-agent/pull/275
> Remove jdk17-preview from one more image

- updatecli/updatecli.d/remoting.yaml
Signed-off-by: Damien Duportal <damien.duportal@gmail.com>
> chore(updatecli) track version of remoting

- 17/bullseye/Dockerfile
Remove duplicate ARG VERSION for JDK17/Debian Bullseye. Fix comment for package manager call.
> Remove duplicate ARG VERSION, Fix comment for debian package manager

- build.ps1
The publication of the windows version of the  -11 and -12 failed with the following errors:
```
12:46:43 powershell.exe : An image does not exist locally with the tag: jenkins/agent
12:46:43  At C:\Jenkins\workspace\ker-agent_3107.v665000b_51092-11@tmp\durable-ee35770b\powershellWrapper.ps1:3 char:1
12:46:43  + & powershell -NoProfile -NonInteractive -ExecutionPolicy Bypass -Comm ...
12:46:43  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
12:46:43      + CategoryInfo          : NotSpecified: (An image does n...: jenkins/agent:String) [], RemoteException
12:46:43      + FullyQualifiedErrorId : NativeCommandError
12:46:43   
12:46:43  Publishing  => tag=3107.v665000b_51092-11-jdk11-windowsservercore-ltsc2019
12:46:43  The push refers to repository …
```
> hotfix(windows) use proper tagging destination to fix publication

- tests/agent.Tests.ps1
- windows/nanoserver-1809/Dockerfile
This PR does not introduce any change in the images themselves.
It's a cleanup of different leftovers caught while working on #409, https://github.com/jenkinsci/docker-inbound-agent/pull/347 and https://github.com/jenkinsci/docker-ssh-agent/pull/241
> chore(windows) cleanup tooling and nanoserver-1809 `Dockerfile`

- Jenkinsfile
- build-windows-2019.yaml
- build-windows.yaml
- build.ps1
- tests/test_helpers.psm1
- updatecli/updatecli.d/git-windows.yaml
- updatecli/updatecli.d/jdk11.yaml
- updatecli/updatecli.d/jdk17.yaml
- updatecli/updatecli.d/remoting.yaml
- windows/nanoserver/Dockerfile
- windows/windowsservercore/Dockerfile
This PR refactors Jenkinsfile steps in order to facilitate the introduction of Windows LTSC 2022 and future images like in https://github.com/jenkinsci/docker-agent/pull/441.
~As it would have been more difficult to do otherwise, it includes an evolution of the changes of #442 and #444.~
~Extract from https://github.com/jenkinsci/docker-agent/pull/441#issuecomment-1612214991,~
> ~I'd suggest reviewing (and hopefully merging) https://github.com/jenkinsci/docker-agent/pull/442 then https://github.com/jenkinsci/docker-agent/pull/444 then [this PR]~
These PRs have since been merged.
Replay with all tests passing: https://ci.jenkins.io/job/Packaging/job/docker-agent/job/PR-445/4/
Last version: https://ci.jenkins.io/job/Packaging/job/docker-agent/job/PR-445/55/
```[tasklist]
```
> refactor(build): factorize Jenkinsfile steps

- .github/dependabot.yml
Follow-up of #445 
```[tasklist]
```
> chore(dependabot): new folders since refactoring

- tests/agent.Tests.ps1
This test concerns "docker-agent" images, not "docker-inbound-agent".
```[tasklist]
```
> chore(test): correct `CONTAINERNAME`

- Jenkinsfile
This PR fixes https://github.com/jenkinsci/docker-agent/issues/451 (Suggested in https://github.com/jenkinsci/docker-agent/pull/459 but not applied)
```[tasklist]
```
> feat: add a `nanoserver-ltsc2019` image

- build-windows.yaml
This PR adds jdk21 variants for Windows images.
https://ci.jenkins.io/job/Packaging/job/docker-agent/job/PR-518/3/
```[tasklist]
```
> feat(Windows): add Java 21

- docker-bake.hcl
This PR removes an unused group.
```[tasklist]
```
> cleanup: remove "windows" group from docker-bake.hcl

- README.md
- README_inbound-agent.md
This PR reformulates the intro and replaces remaining `master` occurrences by `controller`.
N/A
```[tasklist]
```
> chore(doc): small cleanup

- build.ps1
This PR replaces the conversion of docker compose config output (currently buggy, not converted to json even with the appropriate tag) with `ConvertFrom-Json` then queried with `<object>.PSObject.Properties` by directly retrieving the images from the YAML output with `yq`.
It also removes the error silencing of the docker compose config call.
Fixes #780 
Replay: https://ci.jenkins.io/job/Packaging/job/docker-agent/view/change-requests/job/PR-781/4/console
```[tasklist]
```
> fix(windows): directly retrieve images from docker compose config output with `yq`

- updatecli/updatecli.d/jdk11.yaml
- updatecli/updatecli.d/jdk17.yaml
- updatecli/updatecli.d/jdk21.yaml
This PR fixes Windows targets in jdk manifests.
Follow-up of:
- #787
Will fixes:
- #796
Will closes:
- #795
Ran updatecli diff locally.
```[tasklist]
```
> chore(updatecli): fix Windows targets in jdk manifests

- Jenkinsfile
Ref. https://github.com/jenkins-infra/helpdesk/issues/4192#issuecomment-2250829917
>  chore(Jenkinsfile) increase DockerHub rate limit with authentication

- .github/dependabot.yml
This PR removes dependencies tracked by updatecli.
Ref:
- https://github.com/jenkinsci/docker-agent/pull/866#discussion_r1773089915
> cleanup: remove from dependabot the dependencies tracked by updatecli

- Jenkinsfile
This PR sets this environment variable like what was done before and like what is done in docker-ssh-agent.
Fixup of:
- #827 
A replay is in progress on trusted.ci.jenkins.io
> chore(Jenkinsfile): set `ON_TAG` to `true` to publish tagged versions of the images

- README_agent.md
Fix broken link in the documentation.
Confirmed current link is broken.  Confirmed the pull request fixes the broken link.
> docs: update README_agent.md to fix broken link

- Jenkinsfile
Fixup of #960
The release https://github.com/jenkinsci/docker-agent/releases/tag/3301.v4363ddcca_4e7-2 required a few manual fixes to be successful.
This PR cherry picks these changes for the next release:
- trusted.ci.jenkins.io does not have the Kubernetes plugin installed and as such failed to recognize the `kubernetesAgent()` directive. It is replaced by `agent()` which does the same but for "normal agents" (ref. https://www.jenkins.io/doc/pipeline/steps/workflow-basic-steps/#retry-retry-the-body-up-to-n-times)
- trusted.ci.jenkins.io does not have any `spot` or `nonspot` labels. As such, the `spotAgentSelector()` function should return early, if running in trusted, with the provided label "as it".
=> tested with replays, the release was published with success in DockerHub: …
> chore(Jenkinsfile) fixes to allow trusted.ci publishing images

- updatecli/updatecli.d/remoting.yaml
#985 led to the creation of #987, which was wrong.
This was detected  by @MarkEWaite and @dduportal .
This pull request addresses an issue in the `remoting.yaml` file where the `replacepattern` was not correctly handling trailing content after the version string in the `README.md` file. The change modifies the `replacepattern` to use `$3` instead of `$2` to ensure that any content following the version string is properly included in the replacement.
* **Bug Fix**: Corrects the `replacepattern` in `remoting.yaml` to properly include trailing content when updating the version in `README.md`.
* **Configuration Update**: Updates the `remoting.yaml` file to ensure accurate version replacement in the target file.
* **updatecli/updatecli.d/remoting.yaml**
* Modified `replacepattern` from …
> chore(updatecli): Correct replace pattern in remoting.yaml to include trailing content

- updatecli/scripts/ubi9-latest-tag.sh
This PR is a follow-up to #989, #979, and #883.
This pull request addresses an issue in the `ubi9-latest-tag.sh` script, which is responsible for determining the latest UBI9 tag. The original script logic was flawed in how it parsed the JSON response from the registry API to identify the correct tag. This update modifies the `jq` command to more accurately extract the latest tag associated with the "latest" tag, specifically looking for tags that contain a hyphen (which indicates a long-form tag) and are not named "latest".
* **Bug Fix**: The pull request fixes a bug in the `ubi9-latest-tag.sh` script that caused it to incorrectly identify the latest UBI9 tag.
* **Improved Tag Parsing**: The `jq` command in the script has been updated to more accurately parse the JSON response and extract …
> chore(updatecli): fix UBI9 script
